kind: Deployment
apiVersion: apps/v1
metadata:
  name: restate-go
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: restate-multicast
    spec:
      containers:
      - image: quay.io/kennedn/restate-go:latest
        name: restate-go
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: restate-go-config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      volumes:
      - name: restate-go-config-volume
        secret:
          defaultMode: 420
          secretName: restate-go-config
