kind: Deployment
apiVersion: apps/v1
metadata:
  name: restate-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/kennedn/restate-go:latest
          name: restate-go
          ports:
            - containerPort: 8080
		  volumeMounts:
		  - name: restate-go-config-volume
			mountPath: /app/config.yml
			subPath: config.yml
		volumes:
		- name: restate-go-config-volume
		  configMap:
			defaultMode: 420
			name: restate-go-config
