apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: restate-multicast
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "restate-multicast",
    "type": "macvlan",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.1.0/24",
      "rangeStart": "192.168.1.203",
      "rangeEnd": "192.168.1.208"
    }
  }'
